services:

  postgres:
    container_name: go-todo-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
    volumes:
      - go_postgres_storage:/data/postgres
    ports:
      - '5433:5432'

volumes:
  go_postgres_storage: